version: "3"

services:
  kartmayhem-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: QWElkj132!
      MSSQL_PID: Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - kartmayhemnet

  kartmayhem-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=kartmayhem-db,1433;Database=KartMayhem;User=sa;Password=QWElkj132!;ConnectRetryCount=0;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:8080
    networks:
      - kartmayhemnet
    links:
      - kartmayhem-db
    depends_on:
      - kartmayhem-db

networks:
  kartmayhemnet:
    driver: bridge